### ISSUE TITLE
Can't compile/build

### ISSUE THREAD

**Issue by pugzit** [mohammad92/android_kernel_samsung_r7#1]
here is my log : 

 B U I L D - M E N U 
1. Build
2. Clean
3. Make flashable zip
4. Exit
Enter choice [ 1 - 4] 1
1) r7

Select variant: 1
r7 selected
Press [Enter] key to continue...
***** Compiling kernel *****
make: Entering directory '/home/r7/exynos9810'
make[1]: Entering directory '/home/r7/exynos9810/out'
  GEN     ./Makefile
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
drivers/battery_v2/Kconfig:122:warning: ignoring type redefinition of 'ENG_BATTERY_CONCEPT' from 'boolean' to 'tristate'
drivers/samsung/misc/Kconfig:7:warning: ignoring type redefinition of 'SEC_DEBUG_TSP_LOG' from 'tristate' to 'boolean'
drivers/samsung/misc/Kconfig:87:warning: leading whitespace ignored
#
# configuration written to .config
#
make[1]: Leaving directory '/home/r7/exynos9810/out'
make: Leaving directory '/home/r7/exynos9810'
make: Entering directory '/home/r7/exynos9810'
make[1]: Entering directory '/home/r7/exynos9810/out'
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
drivers/battery_v2/Kconfig:122:warning: ignoring type redefinition of 'ENG_BATTERY_CONCEPT' from 'boolean' to 'tristate'
drivers/samsung/misc/Kconfig:7:warning: ignoring type redefinition of 'SEC_DEBUG_TSP_LOG' from 'tristate' to 'boolean'
drivers/samsung/misc/Kconfig:87:warning: leading whitespace ignored
arch/arm64/Makefile:27: ld does not support --fix-cortex-a53-843419; kernel may be susceptible to erratum
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
  CHK     include/config/kernel.release
Traceback (most recent call last):
  File "/home/r7/clang-r353983c/bin/clang", line 192, in <module>
    main(sys.argv)
  File "/home/r7/clang-r353983c/bin/clang", line 188, in main
    cw.invoke_compiler()
  File "/home/r7/clang-r353983c/bin/clang", line 162, in invoke_compiler
    os.execv(self.argv0, self.execargs)
OSError: [Errno 8] Exec format error
Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
/home/r7/exynos9810/Makefile:1216: recipe for target 'prepare-compiler-check' failed
make[1]: *** [prepare-compiler-check] Error 1
make[1]: *** Waiting for unfinished jobs....
  UPD     include/config/kernel.release
make[1]: *** wait: No child processes.  Stop.
Makefile:152: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
make: Leaving directory '/home/r7/exynos9810'
Kernel STUCK in BUILD!, Press [Enter] key to return to Main menu...

**Comment by mohammad92** [comment]
I will check soon

**Comment by pugzit** [comment]
Thank you sir.. additional information, actually im using the android phone which im trying the kernel to compile. Using ubuntu distro in Linux Deploy.

**Comment by mohammad92** [comment]
Ok this is might be the issue, my repo tested with PC and Ubuntu configured to build android stuff
